// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCxNfCOZAjlNMVZJoSToXO8Vg0Xifwsp0E',
    appId: '1:974944803691:web:caa1b9f470d51bf46c0a2e',
    messagingSenderId: '974944803691',
    projectId: 'flutter-project-91966',
    authDomain: 'flutter-project-91966.firebaseapp.com',
    storageBucket: 'flutter-project-91966.firebasestorage.app',
    measurementId: 'G-DB13051BYX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-BbyaIRGNd9_FSzzfGjhXzXZTJQ0ThTM',
    appId: '1:974944803691:android:0df53691308032816c0a2e',
    messagingSenderId: '974944803691',
    projectId: 'flutter-project-91966',
    storageBucket: 'flutter-project-91966.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD5Wq5drC1wNfNqa1X5rsX4vMST3S0A8Hs',
    appId: '1:974944803691:ios:f85e9b1aa682f1406c0a2e',
    messagingSenderId: '974944803691',
    projectId: 'flutter-project-91966',
    storageBucket: 'flutter-project-91966.firebasestorage.app',
    iosBundleId: 'com.example.profil',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD5Wq5drC1wNfNqa1X5rsX4vMST3S0A8Hs',
    appId: '1:974944803691:ios:f85e9b1aa682f1406c0a2e',
    messagingSenderId: '974944803691',
    projectId: 'flutter-project-91966',
    storageBucket: 'flutter-project-91966.firebasestorage.app',
    iosBundleId: 'com.example.profil',
  );
}
